#include <conio.h>
#include <iostream.h>

main(){
	int nilai[5]; // variable nilai yang bertipe data int dan berbentuk array dengan maksimal 5 data (0-4)

   nilai[0] = 90;
   nilai[1] = 80;
   nilai[2] = 85;
   nilai[3] = 87;
   nilai[4] = 98;

   cout << nilai[0] << endl;
   cout << nilai[1] << endl;
   cout << nilai[2] << endl;
   cout << nilai[3] << endl;
   cout << nilai[4] << endl;

   getch();
}
