#include <iostream.h>
#include <conio.h>

int main() {
    int a, b; // deklarasi variable
    a = 7;
    b = 2;

    // menampilkan penjumlahan a dan b
    cout << "a + b = " << (a + b) << endl;

    // menampilkan pengurangan a dan b
    cout << "a - b = " << (a - b) << endl;

    // menampilkan perkalian a dan b
    cout << "a * b = " << (a * b) << endl;

    // menampilkan pembagian a dan b
    cout << "a / b = " << (a / b) << endl;

    // menampilkan modulus a dan b
    cout << "a % b = " << (a % b) << endl;

    getch();
}